server:
  port: 8003

mybatis:
  config-location: classpath:mybaits/mybatis.cfg.xml
  type-aliases-package: com.springcloud.entities
  mapper-locations: classpath:mybaits/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: root
    dbcp2:
      min-idle: 5     #数据库连接池的最小维持连数
      initial-size: 5  #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间
eureka: #客户端注册进eureka服务表内
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #集群
  instance:  #注册进Eureka后的名称
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true  #访问路径可以显示IP地址
#追击服务信息的描述
info:
  app.name: microservicecloud-dept
  company.name: www.yonyou.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
