server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #集群
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: springcloud-microcloud
  company.name: www.springcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#路由配置
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: "*" #  *是将所有微服务名都屏蔽，也可以单个
  prefix: /springcloud
